In [49]:
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, precision_score, recall_score, classification_report, confusion_matrix

In [50]:
iris = pd.read_csv("IRIS.csv")
iris.sample()

    sepal_length  sepal_width  petal_length  petal_width          species
66           5.6          3.0           4.5          1.5  Iris-versicolor

In [51]:
# convert 3 species into 0, 1, 2
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
iris["species"] = le.fit_transform(iris["species"])
iris.sample(5)

     sepal_length  sepal_width  petal_length  petal_width  species
148           6.2          3.4           5.4          2.3        2
19            5.1          3.8           1.5          0.3        0
130           7.4          2.8           6.1          1.9        2
31            5.4          3.4           1.5          0.4        0
52            6.9          3.1           4.9          1.5        1

In [63]:
X = iris.drop("species", axis = 1)
y = iris["species"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size = 0.5, random_state = 42
)

In [53]:
# Logistic regression
lr = LogisticRegression(max_iter = 1000)
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)

In [54]:
# KNN
knn = KNeighborsClassifier(n_neighbors = 5)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)

In [55]:
# Naive bayes (Gaussian)
gb = GaussianNB()
gb.fit(X_train, y_train)
y_pred = gb.predict(X_test)

In [69]:
models = {"Logistic Regression": lr, "KNeighborsClassifier": knn, "GaussianNB": gb}

for name, model in models.items():
    y_pred = model.predict(X)
    print(f"\n {name}")
    print(f"accuracy score: {accuracy_score(y, y_pred)}")
    print(f"cm: {confusion_matrix(y, y_pred)}")
    print(f"classification report:\n {classification_report(y, y_pred)}")

 Logistic Regression
accuracy score: 0.9666666666666667
cm: [[50  0  0]
 [ 0 48  2]
 [ 0  3 47]]
classification report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        50
           1       0.94      0.96      0.95        50
           2       0.96      0.94      0.95        50

    accuracy                           0.97       150
   macro avg       0.97      0.97      0.97       150
weighted avg       0.97      0.97      0.97       150


 KNeighborsClassifier
accuracy score: 0.9533333333333334
cm: [[50  0  0]
 [ 0 50  0]
 [ 0  7 43]]
classification report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        50
           1       0.88      1.00      0.93        50
           2       1.00      0.86      0.92        50

    accuracy                           0.95       150
   macro avg       0.96      0.95      0.95       150
weighted avg       0.96      0.95      0.95       150


 GaussianNB
accuracy score: 0.9533333333333334
cm: [[50  0  0]
 [ 0 47  3]
 [ 0  4 46]]
classification report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        50
           1       0.92      0.94      0.93        50
           2       0.94      0.92      0.93        50

    accuracy                           0.95       150
   macro avg       0.95      0.95      0.95       150
weighted avg       0.95      0.95      0.95       150

In [ ]:
# Conclusion
# Logistic Regression(0.967), KNN(0.954), Naive(0.954)
# so the best model is Logistic Regression